version: '3'

services:
  ccsmartproxy:
    image: thorlogic/ccsmartproxy
    container_name: ccsmartproxy
    ports:
      - "8116:80"
    volumes:
      - /docker/ccsmartproxy:/var/log/nginx/log

  cardiac:
    image: thorlogic/cardiac
    container_name: cardiac
    ports:
      - "8117:8000"
    restart: always

  bpcentile:
    image: thorlogic/bpcentile
    container_name: bpcentile
    ports:
      - "8118:8001"
    restart: always


  growth-chart:
    image: thorlogic/growth-chart
    container_name: growth-chart
    ports:
      - "8119:9000"
    restart: always
